# Generated by Django 5.2.17 on 2026-09-21 04:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_product_alter_sale_region_salesorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='ba',
        ),
        migrations.AddField(
            model_name='sale',
            name='sales_rep',
            field=models.ForeignKey(default=django.utils.timezone.now, limit_choices_to={'role': 'SALES_REP'}, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
