# Generated by Django 5.2.17 on 2026-09-21 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_alter_region_options_and_more'),
        ('inventory', '0002_alter_inventoryitem_ba_alter_inventoryitem_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='ba',
            new_name='sales_rep',
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('sales_rep', 'product')},
        ),
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('MAIN_DEPOT', 'Main Depot / Warehouse'), ('TRANSIT_VAN', 'Transit Van / Sales Rep')], default='TRANSIT_VAN', max_length=20)),
                ('assigned_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Rep Acceptance'), ('ACCEPTED', 'Accepted into Van Stock'), ('REJECTED', 'Rejected / Damaged in Transit')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to='inventory.inventorylocation')),
                ('source_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to='inventory.inventorylocation')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cases_quantity', models.PositiveIntegerField(default=0)),
                ('cartons_quantity', models.PositiveIntegerField(default=0)),
                ('packs_quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransfer')),
            ],
        ),
    ]
