# Generated by Django 5.0.6 on 2026-09-16 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('accuracy_m', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual check-in'), ('PASSIVE', 'Passive background ping')], default='MANUAL', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ba', models.ForeignKey(limit_choices_to={'role': 'BA'}, on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='catalog.region')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
